# import pyttsx3
# engine = pyttsx3.init()
# # # text_to_speak = "Hello, DJ! This is text-to-speech in Python."
# # engine.say('i am a devil of my word ')
# # engine.runAndWait()
# name = ['rahul','priti']
# for i in name:
#        pyttsx3.init().say(f'the name is {name}')
# engine.runAndWait()

import pyttsx3

# name = ['rahul', 'priti']
engine = pyttsx3.init()

# for n in name:
pyttsx3.init().say(f'goodevening boss, how can i help you ?')

engine.runAndWait()
